name: Validate PR Title (Conventional Commits)

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-title:
    if: >-
      ${{ github.actor != 'release-please[bot]' &&
          github.actor != 'dependabot[bot]' &&
          github.event.pull_request.user.login != 'release-please[bot]' &&
          github.event.pull_request.user.login != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title using Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


