name: Validate PR Title (Conventional Commits)

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title using Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            [
              "feat",
              "fix",
              "perf",
              "docs",
              "style",
              "refactor",
              "test",
              "build",
              "ci",
              "revert",
              "chore"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


